In [3]:
import numpy as np
list1 = [1,2,3,4]
arr1 = np.array(list1)
print(arr1)

[1 2 3 4]


In [4]:
import numpy as np
list1 = [1,2,3,4]
arr1 = np.array(list1)
print(arr1.ndim)

1


In [5]:
import numpy as np

ar = np.array([1,2,3,4,5])
print(ar)

[1 2 3 4 5]


In [6]:
import numpy as np

ar = np.array([1,2,3,4,5])
print(ar[0])

1


In [7]:
import numpy as np

ar = np.array([1,2,3,4,5])
print(ar[-1])

5


In [8]:
import numpy as np

ar = np.array([1,2,3,4,5])
print(ar.ndim)

1


In [9]:
import numpy as np

ar = np.array([1,2,3,4,5])
print(ar.size)

5


In [10]:
list1=[1,2,3,4]
arr1=np.array(list1)
print(arr1*2)

[2 4 6 8]


In [11]:
list1=[1,2,3,4]
arr1=np.array(list1)
print(list1*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [13]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
print(a)

[[1 4]
 [2 9]
 [3 6]
 [3 5]]


In [17]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
a[0]


array([1, 4])

In [16]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
a[1]

array([2, 9])

In [21]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
print(a[2][0])

3


In [24]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
print(a[2][1])

6


In [26]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
a.ndim

2

In [27]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
a.dtype

dtype('int64')

In [28]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
a.size

8

In [29]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
a.shape

(4, 2)

In [30]:
import numpy as np
b=np.array([[[1,4,8],[2,9,9],[3,6,9],[3,5,4]]])
b

array([[[1, 4, 8],
        [2, 9, 9],
        [3, 6, 9],
        [3, 5, 4]]])

In [32]:
import numpy as np
b=np.array([[[1,4,8],[2,9,9],[3,6,9],[3,5,4]]],dtype=np.float64)
b

array([[[1., 4., 8.],
        [2., 9., 9.],
        [3., 6., 9.],
        [3., 5., 4.]]])

In [34]:
import numpy as np
b=np.array([[[1,4,8],[2,9,9],[3,6,9],[3,5,4]]])
print(b[0][0][0])

1


In [35]:
import numpy as np
b=np.array([[[1,4,8],[2,9,9],[3,6,9],[3,5,4]]],dtype=np.float64)
b.ndim

3

In [36]:
import numpy as np
b=np.array([[[1,4,8],[2,9,9],[3,6,9],[3,5,4]]],dtype=np.float64)
b.dtype

dtype('float64')

In [37]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
c=a.reshape(2,4)
print(c)

[[1 4 2 9]
 [3 6 3 5]]


In [38]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
c.ravel()

array([1, 4, 2, 9, 3, 6, 3, 5])

In [40]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
print(a.min())

1


In [41]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
print(a.max())

9


In [43]:
import numpy as np
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
import numpy as np
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
import numpy as np
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
import numpy as np
np.arange(0,25,5)

array([ 0,  5, 10, 15, 20])

In [50]:
import numpy as np
np.linspace(1,10,19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [53]:
import numpy as np
b=np.linspace(1,10,19)
print(b.sum())

104.5


In [55]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
print(a.sum())

33


In [58]:
import numpy as np
a=np.array([[1,4.1],[2,9],[3,6],[3,5]])
print(a.sum(axis=0))

[ 9.  24.1]


In [59]:
import numpy as np
a=np.array([[1,4.1],[2,9],[3,6],[3,5]])
print(a.sum(axis=1))

[ 5.1 11.   9.   8. ]


In [60]:
import numpy as np
a=np.array([[1,4],[25,9],[36,64],[81,16]])
np.sqrt(a)

array([[1., 2.],
       [5., 3.],
       [6., 8.],
       [9., 4.]])

In [62]:
import numpy as np
a=np.array([[1,4],[2,9],[3,6],[3,5]])
print(np.mean(a))

4.125


In [65]:
import numpy as np
a=np.array([[1,2],[3,4]])
y=np.array([[2,4],[5,6]])
z=x+y
z


array([[ 3,  6],
       [ 8, 10]])

In [66]:
import numpy as np
a=np.array([[1,2],[3,4]])
y=np.array([[2,4],[5,6]])
m=x*y
m


array([[ 2,  8],
       [15, 24]])

In [67]:
import numpy as np
a=np.array([[1,2],[3,4]])
y=np.array([[2,4],[5,6]])
x.dot(y)


array([[12, 16],
       [26, 36]])

In [69]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1.dtype)

int64


In [70]:
import numpy as np
arr2=np.array([1.1,2.1,3.1,4.1,5.1])
print(arr2.dtype)

float64


In [71]:
import numpy as np
arr3=np.array(["a","b","c"])
print(arr3.dtype)

<U1


In [72]:
import numpy as np
arr4=np.array([1,2,3,4,5],dtype=np.int64)
print(arr4.dtype)

int64


In [74]:
import numpy as np
arr6=np.array([1,2,3],dtype="i2")
print(arr6.dtype)

int16


In [75]:
import numpy as np
arr7=np.array([1,2,3,4,5],dtype=np.int8)
print(arr7.dtype)

int8


In [76]:
import numpy as np
arr8=arr7.astype(np.float16)
print(arr8.dtype)

float16


In [77]:
import numpy as np
arr9=arr7.astype(np.uint16)
print(arr9.dtype)

uint16


In [78]:
import numpy as np
list=[1,2,3,4]
arr1=np.array(list)
arr1

array([1, 2, 3, 4])

In [79]:
import numpy as np
tuple=[10,20,30]
arr11=np.array(tuple)
arr11

array([10, 20, 30])

In [80]:
import numpy as np
arr12=np.zeros(5)
arr12

array([0., 0., 0., 0., 0.])

In [81]:
import numpy as np
arr13=np.zeros([1,2])
arr13

array([[0., 0.]])

In [82]:
import numpy as np
arr14=np.zeros([3,2,4])
arr14

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [84]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(arr[1:])

[[3 4 5]
 [4 5 6]]


In [2]:
import numpy as np
array = np.array([1, 5, 8, 12, 20, 3])
y = array > 10 
filtered_array = array[y] 
print(array)           
print(filtered_array) 

[ 1  5  8 12 20  3]
[12 20]


In [4]:
import numpy as np
array = np.array([1, 5, 8, 12, 20, 3])
x = (array > 5) &(array<15)
y= array[x] 
print(array)           
print(y) 

[ 1  5  8 12 20  3]
[ 8 12]


In [1]:
import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np
identity_matrix=np.eye(3,4,dtype=int)
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [4]:
import numpy as np
rectangular_matrix=np.eye(3,5)
print(rectangular_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [5]:
import numpy as np
matrix=np.eye(4,k=1)
print(matrix)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [6]:
import numpy as np
arr=np.empty((2,3))
print(arr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.20160575e-306 1.06811354e-306 0.00000000e+000]]


In [7]:
import numpy as np
arr=np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [8]:
import numpy as np
a=np.array([[4,7],[2,6]])
a_inv=np.linalg.inv(a)
print(a)
print(a_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [10]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))

21


In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.mean(arr))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))
print(np.max(arr))
print(np.max(arr,axis=0))
print(np.max(arr,axis=1))
print(np.min(arr))
print(np.min(arr,axis=0))
print(np.min(arr,axis=1))

21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
6
[4 5 6]
[3 6]
1
[1 2 3]
[1 4]


In [16]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
dot=np.dot(a,b)
print(dot)

32


In [17]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
dot=np.dot(a,b)
print(dot)

[[19 22]
 [43 50]]
